name: Terraform EC2 Instance Creation

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3  # Use the latest stable version
      
      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.0.0'  # Specify your Terraform version here

      # Step 3: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'  # Change to your desired region

      # Step 4: Configure SSH (Add SSH key to the machine)
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ACCESS_KEY_SSH }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # Step 5: Initialize Terraform (only once)
      - name: Terraform Init
        run: |
          terraform init
          terraform validate

      # Step 6: Checkout the Terraform repository containing the EC2 config
      - name: Checkout Terraform repository
        run: |
          git clone git@github.com:bh-gaur/terraform.git
          cd terraform/AWS/EC2/

      # Step 7: Plan and Apply Terraform deployment
      - name: Terraform Plan & Apply
        run: |
          cd terraform/AWS/EC2/
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
